#include "Telemetry/TelemetryObjects/Controller/ButtonATelemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonBTelemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonXTelemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonYTelemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonL1Telemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonL2Telemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonR1Telemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonR2Telemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonUpTelemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonDownTelemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonLeftTelemetry.h"
#include "Telemetry/TelemetryObjects/Controller/ButtonRightTelemetry.h"

#include "Axis1Telemetry.h"
#include "Axis2Telemetry.h"
#include "Axis3Telemetry.h"
#include "Axis4Telemetry.h"