name: Makefile CI

on:
  push:
    branches: [ "" ]
  pull_request:
    branches: [ "" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make configure script executable
      run: chmod +x Testing/configure

    - name: Configure
      run: Testing/configure
    
    - name: Install dependencies
      run: make -C Testing
